// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE


var videos = /* :: */[
  /* record */[
    /* id */65432445,
    /* title */"The Chamber"
  ],
  /* :: */[
    /* record */[
      /* id */675465,
      /* title */"Fracture"
    ],
    /* :: */[
      /* record */[
        /* id */70111470,
        /* title */"Die Hard"
      ],
      /* :: */[
        /* record */[
          /* id */654356453,
          /* title */"Bad Boys"
        ],
        /* [] */0
      ]
    ]
  ]
];

export {
  videos ,
  
}
/* No side effect */
