// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as List from "bs-platform/lib/es6/list.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";
import * as Common$Prof from "./Common.bs.js";

function prep(_index, _list) {
  while(true) {
    var list = _list;
    var index = _index;
    if (index !== 15) {
      _list = List.rev_append(list, list);
      _index = index + 1 | 0;
      continue ;
      
    } else {
      return list;
    }
  };
}

var v = prep(0, Common$Prof.videos);

var start = Date.now();

var result = List.fold_left((function (dict, video) {
        dict[Pervasives.string_of_int(video[/* id */0])] = video[/* title */1];
        return dict;
      }), { }, v);

console.log("reasonml", Date.now() - start);

export {
  prep ,
  v ,
  start ,
  result ,
  
}
/* v Not a pure module */
