// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE

import * as Belt_List from "bs-platform/lib/es6/belt_List.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";
import * as Common$Prof from "./Common.bs.js";
import * as Belt_MapString from "bs-platform/lib/es6/belt_MapString.js";

function prep(_index, _list) {
  while(true) {
    var list = _list;
    var index = _index;
    if (index !== 15) {
      _list = Belt_List.concat(list, list);
      _index = index + 1 | 0;
      continue ;
      
    } else {
      return list;
    }
  };
}

var v = prep(0, Common$Prof.videos);

var start = Date.now();

var result = Belt_List.reduceU(v, Belt_MapString.empty, (function (dict, video) {
        return Belt_MapString.set(dict, Pervasives.string_of_int(video[/* id */0]), video[/* title */1]);
      }));

console.log("reasonml Belt", Date.now() - start);

export {
  prep ,
  v ,
  start ,
  result ,
  
}
/* v Not a pure module */
